# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

php:
  preset: laravel
  disabled:
    - unused_use
  finder:
    not-name:
      - index.php
      - server.php
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
